import JSZip from 'jszip';
import { ProjectFile, ProjectMetadata } from '@/types';

/**
 * Export Service - generates downloadable ZIP files from project files.
 */
export class ExportService {
    static async downloadZip(files: ProjectFile[], metadata: ProjectMetadata): Promise<void> {
        const zip = new JSZip();

        // Add all project files
        files.forEach(file => {
            zip.file(file.path, file.content);
        });

        // Auto-generate a README
        zip.file('README.md', this.generateReadme(metadata, files));

        const blob = await zip.generateAsync({ type: 'blob' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${metadata.name.toLowerCase().replace(/\s+/g, '-')}.zip`;
        a.style.display = 'none';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    private static generateReadme(metadata: ProjectMetadata, files: ProjectFile[]): string {
        return `# ${metadata.name}

${metadata.description}

## Generated by FlashBuild

- **Framework**: ${metadata.framework}
- **Files**: ${files.length}
- **Generated**: ${metadata.createdAt.toLocaleDateString()}

## Getting Started

Open \`index.html\` in your browser to view the application.

## Project Structure

\`\`\`
${files.map(f => f.path).join('\n')}
\`\`\`
`;
    }
}
